#!/usr/bin/env bash
# Write a Bash script that pings an IP address passed as an argument.
ping "$1" -c 5
if [ $# -eq 0 ]
  then
    echo "Usage: 5-is_the_host_on_the_network {IP_ADDRESS}"
    exit 0
fi
