#!/usr/bin/env bash
# This script is displaying "Holberton School" 10 times and bad luck & good luck
for x in {1..100}
do
    if ((x % 3 == 0 && x % 5 == 0 ))
    then
        echo "FizzBuzz"
    elif ((x % 5 == 0))
    then
        echo "Buzz"
    elif ((x % 3 == 0))
    then
        echo "Fizz"
    else
        echo "$x"
    fi
done