#!/usr/bin/env bash
# This script is displaying "Holberton School" 10 times
counter=0
while [ $counter -lt 10 ]
do
  echo "Holberton School $counter"
  let counter=counter+1
  if [[ "$counter" == '9' ]]; then
		echo "Hi"
	fi
done
