#!/usr/bin/env bash
# This script is displaying "Holberton School" 10 times
counter=1
end=9
while [ $end -ge $counter ]
do
  echo "Holberton School"
  let counter++
  if [[ "$counter" == '9' ]]
	then
		echo "Hi"
	fi
done
