#!/usr/bin/env bash
# This script is displaying numbers from 1 to 20 with some special cases
counter=1
while [ $counter -lt 21 ]
do
    echo $counter
    case "$counter" in
    4) echo "bad luck from China"
    ;;
    9) echo "bad luck from Japan"
    ;;
    17) echo "bad luck from Italy"
    ;;
    esac
    let counter++
done
