#!/usr/bin/env bash
# Fix this container so that Nginx is running as the nginx user.

sudo chmod -R 777 /etc/nginx/nginx.conf
sudo chown -R nginx:nginx /etc/nginx/nginx.conf
        sudo -u nginx service nginx restart
