#!/usr/bin/env bash
# Fix this container so that Nginx is running as the nginx user.

pkill apache2
sed -i 's/80/8080/g' /etc/nginx/sites-available/default
chmod -R 777 /etc/nginx/nginx.conf
sudo -u nginx service nginx restart
